Update git submodules
* Update third_party/googletest from branch 'master'
  to c700ea73d6b1308f4ee3760a3c5c87d507763bc4
  - Fuchsia GN build file
    
    This is used by the Fuchsia build.
    
    Change-Id: I538493ad18cdec6765d9d4c1c321d7f0793b2abf
    
  - Use DEBUG_POSTFIX instead of CMAKE_DEBUG_POSTFIX
    
    CMAKE_DEBUG_POSTFIX is a global configuration parameter, and
    changing it pollutes the configuration space for other projects
    that enclose this project.
    
    DEBUG_POSTFIX is better to use since it is a target-specific poperty.
    
    Fixes #1334
    Fixes #1268
    
  - Support JSON output format in addition to XML
    
    This change allows emitting output in JSON format in addition to the
    already supported XML format. The implementation as well as the file
    structure is intentionally modelled after the XML one.
    
  - Merge pull request #1482 from zhangxy988/variant_matcher
    
    Add matcher for std::variant.
  - Merge branch 'variant_matcher' of https://github.com/zhangxy988/googletest into variant_matcher
    
  - Merge branch 'master' into variant_matcher
  - Merge branch 'variant_matcher' of https://github.com/zhangxy988/googletest into variant_matcher
    
  - Add documentation for VariantWith.
    
  - Merge pull request #1483 from gennadiycivil/master
    
    gmock merging -2
  - Merge branch 'master' into master
  - Merge pull request #1423 from pcc/win-libcxx2
    
    Use _CPPUNWIND instead of _HAS_EXCEPTIONS with MSVC.
  - gmock merging -2
    
  - Merge branch 'master' into variant_matcher
  - Merge pull request #1464 from pwnall/death-style
    
    Add preprocessor macro for default death test style.
  - Add matcher for std::variant.
    
  - Switch default death test style back to "fast".
    
    Google Test has recently (02/09/2018) switched the default death test
    style from "fast" to "threadsafe" in
    https://github.com/google/googletest/commit/ec7faa943d7817c81ce7bdf71a21ebc9244dc8de
    
    Threadsafe death tests have been used internally for a while, and are
    proven to be a better default.
    
    However, adopting this better default can be challenging for large
    projects with a significant investment in custom infrastructure built on
    top of Google Test. The same custom infrastructure can make it difficult
    for large projects to switch back to the old default by passing in
    --gtest_death_test_style=fast.
    
    For the reasons above, the default switch is considered too disruptive,
    and this CL reverts it. This CL also introduces the
    GTEST_DEFAULT_DEATH_TEST_STYLE preprocesor macro, which replaces the
    hard-coded default. The macro can be defined in
    gtest/internal/custom/gtest-port.h by projects that are ready to migrate
    to thread-safe death tests.
    
  - Merge branch 'master' into win-libcxx2
  - Merge pull request #1472 from AndersSundmanTobii/master
    
    Removed trailing comma in enum
  - Merge branch 'master' into master
  - Merge pull request #1475 from gennadiycivil/master
    
    merge check - 3
  - merging unittests - 5
    
  - merging unitests - check 4
    
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Merge pull request #1474 from gennadiycivil/master
    
    merging unittests - 2
  - merging unitests, check
    
  - 
    
    merging unittests - 2
  - Merge pull request #1473 from gennadiycivil/master
    
    merging unitests
  - 
    
    merging unitests
  - Merge pull request #1471 from aleksejkozin/patch-1
    
    TEST() arguments are invalid in an example
  - Removed trailing comma in enum
    
  - Merge branch 'master' into patch-1
  - Merge pull request #1466 from pwnall/fix-death-warn
    
    Fix unused function warning on Mac OS.
  - TEST() arguments are invalid in an example
    
    Both names must be valid C++ identifiers, and they should not contain underscore (`_`)
  - Merge branch 'master' into fix-death-warn
  - Merge pull request #1469 from gennadiycivil/master
    
    merges
  - merges
    
  - Fix unused function warning on Mac OS.
    
    As of recently, Google Test fails to compile with the warning below when
    used in projects with strict warning settings.
    
    googletest/src/gtest-death-test.cc:1004:13: error: unused function 'StackGrowsDown' [-Werror,-Wunused-function]
    
  - Merge pull request #1450 from pwnall/fix-printers
    
    Fix std::iscntrl use in gtest-printers.cc
  - Merge branch 'master' into fix-printers
  - Merge pull request #1459 from gennadiycivil/master
    
    cleanup, merges
  - Merge branch 'master' of https://github.com/google/googletest
    
  - cleanup, merges
    
  - Merge pull request #1458 from gennadiycivil/master
    
    cleanup, merges
  - Merge branch 'master' into fix-printers
  - Merge branch 'master' of https://github.com/google/googletest
    
  - cleanup/merges
    
  - Merge pull request #1457 from gennadiycivil/master
    
    merging, cleaning up
  - merging, cleaning up
    
  - Merge pull request #1456 from gennadiycivil/master
    
    merges
  - Merge branch 'master' of https://github.com/google/googletest
    
  - merges
    
  - Merge pull request #1454 from gennadiycivil/master
    
    merges
  - cxxx11
    
  - clang warnings
    
  - clang warnings
    
  - https://travis-ci.org/google/googletest/jobs/340995238
    
  - clang warning 'https://travis-ci.org/google/googletest/jobs/340987201'
    
  - clang warning https://travis-ci.org/google/googletest/jobs/340978022
    
  - merges
    
  - Merge pull request #1452 from gennadiycivil/master
    
     moving JoinAsTuple to internal
  - Merge branch 'master' of https://github.com/google/googletest
    
  - moving JoinAsTuple to internal
    
  - Fix std::iscntrl use in gtest-printers.cc
    
    ContainsUnprintableControlCodes() in gtest-printers.cc passes a char
    argument to std::iscntrl. Although its argument is an int, std::iscntrl
    produces undefined behavior if its argument is not representable as an
    unsigned char. The standard library on Windows asserts that the argument
    is an unsigned char, resulting in an assertion crash on debug builds.
    
  - Merge pull request #1451 from gennadiycivil/master
    
    merges
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Merging, coniniue
    
  - Merge pull request #1449 from gennadiycivil/master
    
    merges
  - merging
    
  - 
    
    merges
  - Merge pull request #1439 from DarthGandalf/assert
    
    Add ability to throw from ASSERT
  - Merge branch 'master' into assert
  - Merge pull request #1446 from tholsapp/master
    
    Fixed typos
  - Merge pull request #1448 from gennadiycivil/master
    
    merges
  - merges
    
    
  - Fixed typos
    
  - Add ability to throw from ASSERT
    
    while not losing benefits of EXPECT, and not killing the whole test,
    as with --gtest_throw_on_failure.
    
    183822976
    
  - Include MSVC14 on PRs as well
  - Merge pull request #1435 from gennadiycivil/master
    
    Code merges
  - Merges and also adding new bazel build mode
    
  - Code merges
    
  - Merge pull request #1434 from gennadiycivil/master
    
    Ability to optionally depend on Abseil plus upstream of 183716547
  - Ability to optionally depend on Abseil plus upstream of 183716547
    
  - Merge pull request #1430 from gennadiycivil/master
    
    Adding tests to googlemock bazel
  - Adding tests to googlemock bazel
    
  - Merge pull request #1429 from gennadiycivil/master
    
    Code merges
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Code merges
    
  - Merge pull request #1428 from lidaobing/patch-2
    
    Update Documentation.md
  - Merge pull request #1426 from stefanosoffia/fix_test_build_gcc7_2_0
    
    Fix test build issue with GCC7.2 (with -Wno-error=)
  - Update Documentation.md
  - Fix test build issue with GCC7.2.
    
  - Use _CPPUNWIND instead of _HAS_EXCEPTIONS with MSVC.
    
    _HAS_EXCEPTIONS is specific to the MSVC STL and defining it to 0 causes
    problems with libc++, so libc++ users may leave it undefined. This can
    cause GTEST_HAS_EXCEPTIONS to be defined incorrectly if the user has
    disabled exceptions via the compiler, which can lead to build errors.
    
    _CPPUNWIND is a builtin macro provided by the compiler so it should
    work with both STLs.
    
  - Pass -EHs-c- to disable exceptions with MSVC.
    
  - Update README.md
  - Remove Visual Studio 10,11,12 from build matrix
  - Merge pull request #1421 from gennadiycivil/master
    
     upstream cl 182543808
  - placating gcc and its overzeauls size comparison warnings
    
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Merge pull request #1418 from gennadiycivil/master
    
    Many code merge/upstream changes
  - upstream cl 182543808
    
  - Merge branch 'master' of https://github.com/google/googletest
    
  - revert, lets get this compiled
    
  - Merge pull request #1410 from pcc/win-libcxx
    
    Check whether _MSC_VER is defined when detecting presence of cxxabi.h…
  - 
    
    Many code merge/upstream changes
  - Merge branch 'master' into win-libcxx
  - Merge pull request #1417 from gennadiycivil/master
    
     merges, cl/155419551 and others
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Merging, upstream http://cl/182836545
    
    
  - 
    
    more code merge
  - merges, cl/155419551 and other
    
    
  - Merge pull request #1415 from gennadiycivil/master
    
    code merge
  - more merging
    
  - merging
    
  - 
    
    code merge
  - Merge pull request #1401 from eidosmontreal/support_xboxone
    
    Added support for WINAPI_PARTITION_TV_TITLE to support XboxOne applications
  - Merge branch 'master' into support_xboxone
  - Merge branch 'master' into win-libcxx
  - Merge pull request #1412 from gennadiycivil/master
    
    Adding python tests to Bazel build file.
  - 
    
    Adding python tests to Bazel build file. 
  - Merge pull request #1407 from ted-xp/master
    
    Expose ScopedTrace utility in public interface
  - Use fully qualified  in examples
    
  - Document ScopedTrace utility
    
  - Check whether _MSC_VER is defined when detecting presence of cxxabi.h under libc++.
    
    If _MSC_VER is defined, it means that we are using the Microsoft
    ABI, so cxxabi.h (which is associated with the Itanium ABI) will not
    be available.
    
  - Expose ScopedTrace utility in public interface
    
  - Merge pull request #1402 from gennadiycivil/master
    
    Code merging
  - Reverting some changes, need to make the merge compile
    
  - Reverting some changes, need to make the merge compile
    
  - Reverting some changes, need to make the merge compile
    
  - Reverting some changes, need to make the merge compile
    
  - Test files for corresponding changes
    
  - Test files for corresponding changes
    
  - Test files for corresponding changes
    
  - Test files for corresponding changes
    
  - Merge branch 'master' of github.com:gennadiycivil/googletest
    
  - More code merges
    
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Merge branch 'master' into master
  - Code merging
    
  - Merge pull request #1339 from Romain-Geissler/fix-core-dump-shared
    
    Fix double free when building Gtest/GMock in shared libraries and lin…
  - Merge branch 'master' into fix-core-dump-shared
  - Merge pull request #1400 from gennadiycivil/master
    
    Upstream/merge
  - Merge branch 'support_xboxone' of https://github.com/eidosmontreal/googletest into support_xboxone
    
  - Added support for WINAPI_PARTITION_TV_TITLE which is defined on XboxOne
    
  - Merge branch 'support_xboxone' of https://github.com/eidosmontreal/googletest into support_xboxone
    
  - Added support for WINAPI_PARTITION_TV_TITLE which is defined on XboxOne
    
  - continue upstream/merge, etc
    
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Update .travis.yml
    
    Trying to get around mongoDB expired keys, etc
  - Update .travis.yml
  - Update .travis.yml
  - Update .travis.yml
  - Trying to fix travis
    
  - Merge pull request #1399 from gennadiycivil/master
    
    Merging, Upstream cl 103120214
  - Merge branch 'master' of https://github.com/google/googletest
    
  - Upstream cl 103120214
    
    
  - Merge pull request #1398 from gennadiycivil/master
    
    more cleanup
  - More merge, cleanup
    
  - Merge branch 'master' of https://github.com/google/googletest
    
  - More merge, cleanup
    
  - Merge branch 'master' into support_xboxone
    
  - Merge branch 'master' into fix-core-dump-shared
  - Merge branch 'master' into fix-core-dump-shared
  - Fix double free when building Gtest/GMock in shared libraries and linking a test executable with both.
    
  - Merge branch 'master' into support_xboxone
  - Merge branch 'master' into support_xboxone
  - Merge branch 'master' into support_xboxone
  - Merge branch 'master' into support_xboxone
  - Merge remote-tracking branch 'origin/master' into support_xboxone
    
  - Added support for WINAPI_PARTITION_TV_TITLE which is defined on XboxOne